import { AWSAmplify } from '@/providers/aws-amplify';
import { QueryProvider } from '@/providers/query-provider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <AWSAmplify>{children}</AWSAmplify>
        </body>
      </QueryProvider>
    </html>
  );
}
